const ActionTypes = {
    // General
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',

    //HealthbOt
    SAVE_CHAT: 'SAVE_CHAT',
  
    // User
    USER_DATA: 'USER_DATA',
    LOGOUT: 'LOGOUT',
    IS_LOGIN: 'IS_LOGIN',
  
    //Doctors
    GET_ALL_DOCTORS: 'GET_ALL_DOCTORS',
    GET_FAV_DOCTORS: 'GET_FAV_DOCTORS',
    REMOVE_DOC_FROM_FAVORITES: 'REMOVE_DOC_FROM_FAVORITES',
    ADD_DOC_TO_FAVORITES: 'ADD_DOC_TO_FAVORITES',
    CLEAR_ALL_DOCTORS: 'CLEAR_ALL_DOCTORS',
    GET_HOSPITAL_DOCTORS: 'GET_HOSPITAL_DOCTORS',
    ADD_HOSPITAL_DOCTORS: 'ADD_HOSPITAL_DOCTORS',
    UPDATE_HOSPITAL_DOCTORS: 'UPDATE_HOSPITAL_DOCTORS',
    DEL_HOSPITAL_DOCTORS: 'DEL_HOSPITAL_DOCTORS',
    GET_DOCTOR_DETAILS: 'GET_DOCTOR_DETAILS',
    CLEAR_DOCTOR_DETAILS: 'CLEAR_DOCTOR_DETAILS',


    //Appointments
    GET_DOCTOR_APPOINTMENTS: 'GET_DOCTOR_APPOINTMENTS',
    UPDATE_DOCTOR_APPOINTMENTS: 'UPDATE_DOCTOR_APPOINTMENTS',
    GET_MY_APPOINTMENTS: 'GET_MY_APPOINTMENTS',

    //Hospital 
    GET_DASHBOARD_DATA: 'GET_DASHBOARD_DATA',

    //Medical Records
    GET_MEDICAL_RECORDS: 'GET_MEDICAL_RECORDS',
    ADD_MEDICAL_RECORD: 'ADD_MEDICAL_RECORD',
    DEL_MEDICAL_RECORD: 'DEL_MEDICAL_RECORD',
  
  }
  
  export default ActionTypes;