export const Fonts = {
    REGULAR: 'Poppins-Regular',
    BOLD: 'Poppins-Bold',
    MEDIUM: 'Poppins-Medium',
    LIGHT: 'Poppins-Light',
    SEMIBOLD: 'Poppins-SemiBold',
    THIN: 'Poppins-Thin',
    EXTRA_LIGHT: 'Poppins-ExtraLight',
    BLACK: 'Poppins-Black',
    ITALIC: 'Poppins-Italic',
    LIGHT_ITALIC: 'Poppins-LightItalic',
    MEDIUM_ITALIC: 'Poppins-MediumItalic',
    BOLD_ITALIC: 'Poppins-BoldItalic',
    SEMIBOLD_ITALIC: 'Poppins-SemiBoldItalic',
    EXTRA_BOLD_ITALIC: 'Poppins-ExtraBoldItalic',
    EXTRA_LIGHT_ITALIC: 'Poppins-ExtraLightItalic',
    BLACK_ITALIC: 'Poppins-BlackItalic',
    THIN_ITALIC: 'Poppins-ThinItalic',
    EXTRA_BOLD: 'Poppins-ExtraBold',
    THIN: 'Poppins-Thin',
}